name: Spectral
on: [push]
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Spectral
      uses: spectralops/spectral-github-action@v1
      with:
        spectral-dsn: ${{ secrets.SPECTRAL_DSN }}
    - name: Spectral Scan
      run: spectral scan